/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This package imports things required by build scripts, to force `go mod` to see them as dependencies
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	schedulingv1alpha1 "github.com/KunWuLuan/resourcepolicyapi/pkg/apis/scheduling/v1alpha1"
	scheme "github.com/KunWuLuan/resourcepolicyapi/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ResourcePoliciesGetter has a method to return a ResourcePolicyInterface.
// A group's client should implement this interface.
type ResourcePoliciesGetter interface {
	ResourcePolicies(namespace string) ResourcePolicyInterface
}

// ResourcePolicyInterface has methods to work with ResourcePolicy resources.
type ResourcePolicyInterface interface {
	Create(ctx context.Context, resourcePolicy *schedulingv1alpha1.ResourcePolicy, opts v1.CreateOptions) (*schedulingv1alpha1.ResourcePolicy, error)
	Update(ctx context.Context, resourcePolicy *schedulingv1alpha1.ResourcePolicy, opts v1.UpdateOptions) (*schedulingv1alpha1.ResourcePolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, resourcePolicy *schedulingv1alpha1.ResourcePolicy, opts v1.UpdateOptions) (*schedulingv1alpha1.ResourcePolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*schedulingv1alpha1.ResourcePolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*schedulingv1alpha1.ResourcePolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *schedulingv1alpha1.ResourcePolicy, err error)
	ResourcePolicyExpansion
}

// resourcePolicies implements ResourcePolicyInterface
type resourcePolicies struct {
	*gentype.ClientWithList[*schedulingv1alpha1.ResourcePolicy, *schedulingv1alpha1.ResourcePolicyList]
}

// newResourcePolicies returns a ResourcePolicies
func newResourcePolicies(c *TopologyV1alpha1Client, namespace string) *resourcePolicies {
	return &resourcePolicies{
		gentype.NewClientWithList[*schedulingv1alpha1.ResourcePolicy, *schedulingv1alpha1.ResourcePolicyList](
			"resourcepolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *schedulingv1alpha1.ResourcePolicy { return &schedulingv1alpha1.ResourcePolicy{} },
			func() *schedulingv1alpha1.ResourcePolicyList { return &schedulingv1alpha1.ResourcePolicyList{} },
		),
	}
}
