/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This package imports things required by build scripts, to force `go mod` to see them as dependencies
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisschedulingv1alpha1 "github.com/KunWuLuan/resourcepolicyapi/pkg/apis/scheduling/v1alpha1"
	versioned "github.com/KunWuLuan/resourcepolicyapi/pkg/client/clientset/versioned"
	internalinterfaces "github.com/KunWuLuan/resourcepolicyapi/pkg/client/informers/externalversions/internalinterfaces"
	schedulingv1alpha1 "github.com/KunWuLuan/resourcepolicyapi/pkg/client/listers/scheduling/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ResourcePolicyInformer provides access to a shared informer and lister for
// ResourcePolicies.
type ResourcePolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() schedulingv1alpha1.ResourcePolicyLister
}

type resourcePolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewResourcePolicyInformer constructs a new informer for ResourcePolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewResourcePolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredResourcePolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredResourcePolicyInformer constructs a new informer for ResourcePolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredResourcePolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SchedulingV1alpha1().ResourcePolicies(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SchedulingV1alpha1().ResourcePolicies(namespace).Watch(context.TODO(), options)
			},
		},
		&apisschedulingv1alpha1.ResourcePolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *resourcePolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredResourcePolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *resourcePolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisschedulingv1alpha1.ResourcePolicy{}, f.defaultInformer)
}

func (f *resourcePolicyInformer) Lister() schedulingv1alpha1.ResourcePolicyLister {
	return schedulingv1alpha1.NewResourcePolicyLister(f.Informer().GetIndexer())
}
